services:

#   {
#     "currentLevel": "Level_1",
#     "time": 45.5,
#     "tries": 1,
#     "response": 4,
#     "email": "emailPaciente@email.com",
#     "pin": '123456',
# }


#

  db:
    image: mysql:8.0
    container_name: tcc_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tcc_db
    ports:
      - "3307:3306" 
    volumes:
      - tcc_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 240s

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: tcc_back
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db:3306/tcc_db
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head &&
             python seed.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: tcc_front
    restart: unless-stopped
    depends_on:
      - back
    environment:
      NUXT_PUBLIC_API_BASE_URL: http://localhost:8000/api/v1
    ports:
      - "3000:3000"

volumes:
  tcc_mysql_data:
    driver: local



# removendo tudo a força:

# # 1. Descobrir o número do processo (PID) real de cada container no sistema
# PID_FRONT=$(sudo docker inspect -f '{{.State.Pid}}' tcc_front)
# PID_BACK=$(sudo docker inspect -f '{{.State.Pid}}' tcc_back)
# PID_DB=$(sudo docker inspect -f '{{.State.Pid}}' tcc_db)
# echo "PIDs encontrados -> Front: $PID_FRONT | Back: $PID_BACK | DB: $PID_DB"
# # 2. Matar os processos à força sem perguntar pro Docker
# sudo kill -9 $PID_FRONT $PID_BACK $PID_DB
# # 3. Limpar a sujeira (agora o Docker deve conseguir remover, pois eles já morreram)
# sudo docker rm -f tcc_front tcc_back tcc_db

# # Remove o volume do banco de dados antigo e reconstroi td denovo:
# docker volume rm app-web_tcc_mysql_data
# # Remove a rede
# docker network prune -f
# # (Opcional) Tentar subir novamente
# docker-compose build --no-cache
# docker-compose up
