"""add pin to paciente

Revision ID: 3cae688bf6da
Revises: 85acaa7b15f4
Create Date: 2026-05-22 14:51:04.947741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cae688bf6da'
down_revision: Union[str, Sequence[str], None] = '85acaa7b15f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('pin', sa.String(length=6), nullable=True))
    op.create_unique_constraint(None, 'pacientes', ['pin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pacientes', type_='unique')
    op.drop_column('pacientes', 'pin')
    # ### end Alembic commands ###
