"""remove_perguntas_paciente_psicologo_id_pergunta

Revision ID: 3dbf77b1b28b
Revises: 3cae688bf6da
Create Date: 2026-06-07 17:22:48.102156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3dbf77b1b28b'
down_revision: Union[str, Sequence[str], None] = '3cae688bf6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paciente_psicologo')
    op.drop_table('perguntas')
    op.drop_constraint(op.f('respostas_ibfk_2'), 'respostas', type_='foreignkey')
    op.drop_column('respostas', 'id_pergunta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('respostas', sa.Column('id_pergunta', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key(op.f('respostas_ibfk_2'), 'respostas', 'perguntas', ['id_pergunta'], ['id'])
    op.create_table('perguntas',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('pergunta', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('alternativas', mysql.JSON(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('ativo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], name=op.f('perguntas_ibfk_1')),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], name=op.f('perguntas_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('paciente_psicologo',
    sa.Column('id_paciente', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('id_usuario', mysql.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id'], name=op.f('paciente_psicologo_ibfk_1')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('paciente_psicologo_ibfk_2')),
    sa.PrimaryKeyConstraint('id_paciente', 'id_usuario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
