"""remove_perguntas_paciente_psicologo_id_pergunta

Revision ID: 3dbf77b1b28b
Revises: 3cae688bf6da
Create Date: 2026-06-07 17:22:48.102156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3dbf77b1b28b'
down_revision: Union[str, Sequence[str], None] = '3cae688bf6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Remove tabelas e coluna legadas de perguntas.
    Usa IF EXISTS para ser idempotente — funciona em bancos novos
    (criados já sem essas tabelas) e em bancos antigos (que as tinham).
    """
    conn = op.get_bind()

    # 1. Desabilita checagem de FK para poder dropar na ordem correta
    conn.execute(sa.text("SET FOREIGN_KEY_CHECKS=0"))

    # 2. Remove tabela de junção paciente↔psicólogo
    conn.execute(sa.text("DROP TABLE IF EXISTS paciente_psicologo"))

    # 3. Remove tabela de perguntas
    conn.execute(sa.text("DROP TABLE IF EXISTS perguntas"))

    # 4. Remove FK e coluna id_pergunta de respostas (se existirem)
    #    Verifica dinamicamente o nome da constraint no information_schema
    fk_exists = conn.execute(sa.text(
        "SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE "
        "WHERE TABLE_SCHEMA = DATABASE() "
        "AND TABLE_NAME = 'respostas' "
        "AND COLUMN_NAME = 'id_pergunta' "
        "AND REFERENCED_TABLE_NAME IS NOT NULL "
        "LIMIT 1"
    )).fetchone()

    if fk_exists:
        conn.execute(sa.text(
            f"ALTER TABLE respostas DROP FOREIGN KEY `{fk_exists[0]}`"
        ))

    col_exists = conn.execute(sa.text(
        "SELECT COLUMN_NAME FROM information_schema.COLUMNS "
        "WHERE TABLE_SCHEMA = DATABASE() "
        "AND TABLE_NAME = 'respostas' "
        "AND COLUMN_NAME = 'id_pergunta' "
        "LIMIT 1"
    )).fetchone()

    if col_exists:
        conn.execute(sa.text("ALTER TABLE respostas DROP COLUMN id_pergunta"))

    # 5. Reabilita checagem de FK
    conn.execute(sa.text("SET FOREIGN_KEY_CHECKS=1"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('respostas', sa.Column('id_pergunta', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key(op.f('respostas_ibfk_2'), 'respostas', 'perguntas', ['id_pergunta'], ['id'])
    op.create_table('perguntas',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('pergunta', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('alternativas', mysql.JSON(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('updated_by', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('ativo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], name=op.f('perguntas_ibfk_1')),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], name=op.f('perguntas_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('paciente_psicologo',
    sa.Column('id_paciente', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('id_usuario', mysql.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id'], name=op.f('paciente_psicologo_ibfk_1')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name=op.f('paciente_psicologo_ibfk_2')),
    sa.PrimaryKeyConstraint('id_paciente', 'id_usuario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
