"""initial_schema

Revision ID: 4839145c0544
Revises: 
Create Date: 2026-05-01 19:22:53.228494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4839145c0544'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('PSICOLOGO', 'ADMIN', name='role_enum'), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('perguntas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pergunta', sa.String(length=255), nullable=False),
    sa.Column('alternativas', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente_psicologo',
    sa.Column('id_paciente', sa.String(length=36), nullable=False),
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_paciente', 'id_usuario')
    )
    op.create_table('respostas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_paciente', sa.String(length=36), nullable=False),
    sa.Column('resposta', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas')
    op.drop_table('paciente_psicologo')
    op.drop_table('perguntas')
    op.drop_table('pacientes')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
