"""update_resposta_fields

Revision ID: 4dfabb67b33c
Revises: 3dbf77b1b28b
Create Date: 2026-06-07 23:01:11.160707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dfabb67b33c'
down_revision: Union[str, Sequence[str], None] = '3dbf77b1b28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('respostas', sa.Column('currentLevel', sa.String(length=50), nullable=False))
    op.add_column('respostas', sa.Column('time', sa.Float(), nullable=False))
    op.add_column('respostas', sa.Column('tries', sa.Integer(), nullable=False))
    op.add_column('respostas', sa.Column('response', sa.Integer(), nullable=False))
    op.drop_column('respostas', 'cor')
    op.drop_column('respostas', 'resposta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('respostas', sa.Column('resposta', sa.Integer(), nullable=False))
    op.add_column('respostas', sa.Column('cor', sa.String(length=50), nullable=True))
    op.drop_column('respostas', 'response')
    op.drop_column('respostas', 'tries')
    op.drop_column('respostas', 'time')
    op.drop_column('respostas', 'currentLevel')
    # ### end Alembic commands ###
