"""add_id_pergunta_to_resposta

Revision ID: 85acaa7b15f4
Revises: 0dd2019bd3b3
Create Date: 2026-05-21 19:51:04.891490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '85acaa7b15f4'
down_revision: Union[str, Sequence[str], None] = '0dd2019bd3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('respostas', sa.Column('id_pergunta', sa.String(length=36), nullable=True))
    op.alter_column('respostas', 'cor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_foreign_key(None, 'respostas', 'perguntas', ['id_pergunta'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'respostas', type_='foreignkey')
    op.alter_column('respostas', 'cor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('respostas', 'id_pergunta')
    # ### end Alembic commands ###
